POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "rest on VS code",
    "important": true
}

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "",
    "important": true
}